site_name: 'June Klees, Ph.D'
website_logo: site/juneklees-logo.svg
social:
  -
    id: GaclEpHG
    name: Email
    url: 'mailto:compassamerica76@gmail.com'
    icon: site/social-icons/email.svg
  -
    id: pS3DolQNkZ0KMu_0CzHRM
    name: Substack
    url: 'https://junek20.substack.com/'
    icon: site/social-icons/substack-brands-solid-full.svg
nav_cta:
  label: 'Book June'
  link: 'entry::0ecc4df2-a608-450e-aab6-c7d3961c9f65'
footer_content: 'Educator, academic coach, creative consultant, facilitator, podcaster,  speaker, strategist, and humorist (with an 1980s twist) who believes in  the transformative power of explorative applied civics for the greater  well-being of our republic and principled democracy.'
